Guardian Dream "Moisturizer"
MisterX421138/PE pull request #16
Opened 2021-01-02 19:18 UTC by prndev

2021-02-03 06:52 UTC, MisterX421138 requested changes
Mostly text edits.  If you're good with them, just give them your approval.

2021-02-03 06:52 UTC, MisterX421138 commented on src/javascript/dreamsList.js
> +		description: "$guardian is in front of the bathroom mirror, getting ready for the day. The fiddles around with a bottle, pushing dispenser, but the bottle is empty.\n\n@@.guardiandream;“The moistur
```suggestion
		description: "$guardian is in front of the bathroom mirror, getting ready for the day. The fiddles around with a bottle, pushing the dispenser, but the bottle is empty.\n\n@@.guardiandream;“The moisturizer is empty.”@@ she says as she turns to you.\n\nYou suddenly realize that, for some reason, you are naked. $guardian bends down to examine your ball-sack.\n\n@@.guardiandream;“But this are nice and full.”@@ she comments while massaging your balls. @@.guardiandream;“When did you last cum?”@@\n\n“<<print window.timeCode.minutesToStr(playerCode.masturbate.sinceLastCum())>>” you answer truthfully.\n\n@@.guardiandream;“<<if playerCode.masturbate.sinceLastCum() > 2880>>Good. It works best when they are full and ripe.<<else>>That will have to do.<<endif>>”@@\n\n$guardian caresses your caged cock with one hand while positioing the other below, then she squeezes your cage twice. Each time, you can feel your penis pulse, and you spurt a white substance into her hand. Then, $guardian proceeds to apply your personally delivered moisurizer to her face and hands.\n\nIn the cupboard, you notice a strange bottle; its curved dispenser looks very similar to your chastity device. Guardian finishes moistuerizing and then gives you the empty bottle and a dildo.\n\n@@.guardiandream;“Sweetie, please fill up the bottle for me while I am away, will you?”@@\n\nShe kisses you on the forehead and leaves. Your penis twitches in anticipation, looking forward to the anal orgasms.\n",
```

2021-02-03 06:52 UTC, MisterX421138 commented on src/javascript/dreamsList.js
> +		description: "$guardian is in front of the bathroom mirror, getting ready for the day. The fiddles around with a bottle, pushing dispenser, but the bottle is empty.\n\n@@.guardiandream;“The moistur
Some text editing to the dream

2021-02-03 06:52 UTC, MisterX421138 commented on src/Twee/HomeRoutine/Good morning.twee
> +				Your penis is free and with a butt-plug vibrating away on your prostate, it is hard not to start masturbating. Having been teased throughout the night, you come quickly, cum splattering all over
```suggestion
				Your penis is free and the butt-plug is vibrating away on your prostate, and you can't help but start masturbating. Having been teased throughout the night, you orgasm quickly, cum splattering all over your midriff and the sheets.
```

2021-02-03 06:52 UTC, MisterX421138 commented on src/Twee/HomeRoutine/Good morning.twee
> +				In your post-orgasmic daze, you realize you made a terrible mistake: The automatic vibrator has not finished "waking" you up, yet. What had been a pleasurable buzz on your insides a few seconds a
```suggestion
				In your post-orgasmic haze, you realize that you made a terrible mistake: the automatic vibrator has not finished "waking" you up, yet. What had been a pleasurable buzz on your insides a few seconds ago, quickly becomes a source of increasing discomfort.
```

2021-02-03 06:52 UTC, MisterX421138 commented on src/Twee/HomeRoutine/Good morning.twee
> +				@@.hero;I should not have touched myself.@@ you groan to yourself.
```suggestion
				@@.hero;Why did I touch myself.@@ you groan as you squirm from the post-orgasm stimulation.
```

2021-02-03 06:52 UTC, MisterX421138 commented on src/Twee/HomeRoutine/Good morning.twee
> +				You decide to not masturbate in the morning, no matter what.
```suggestion
				Unable to handle the uncomfortable feeling, you resolve to not masturbate in the morning, no matter what.
```

2021-02-06 00:22 UTC, prndev commented
Thank you for looking into it. Thank you for the corrections, they are looking good. This is probably the most comfortable way I ever improved my English skills. :)

2021-03-12 09:58 UTC, prndev commented
As this pull request did not make it into 1.1000, I am closing it for now. I want to try again, opening a pull-request against the main repository next month.

2021-03-12 09:58 UTC, closed without merging